// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1
#pragma warning disable CS8601, CS8618

using System.Text.Json;
using System.Text.Json.Serialization;

namespace EntityResolutionSource.Senzing.Models.Typedef
{
    [JsonConverter(typeof(CandidateKeysForMatchInfoJsonConverter))]
    public class CandidateKeysForMatchInfo
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public IDictionary<string, IList<MatchInfoForAttribute>> Value { get; set; }
    }

    public class CandidateKeysForMatchInfoJsonConverter : JsonConverter<CandidateKeysForMatchInfo>
    {
        public override CandidateKeysForMatchInfo Read(
            ref Utf8JsonReader reader,
            Type typeToConvert,
            JsonSerializerOptions options
        )
        {
            return new CandidateKeysForMatchInfo
            {
                Value = JsonSerializer.Deserialize<
                    IDictionary<string, IList<MatchInfoForAttribute>>
                >(ref reader, options),
            };
        }

        public override void Write(
            Utf8JsonWriter writer,
            CandidateKeysForMatchInfo value,
            JsonSerializerOptions options
        )
        {
            JsonSerializer.Serialize(writer, value.Value, options);
        }
    }
}
