// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1
#pragma warning disable CS8601, CS8618

using System.Text.Json.Serialization;

namespace EntityResolutionSource.Senzing.Models.Typedef
{
    public class CandidateKeysForSearchStatistic
    {
        [JsonPropertyName("FEATURE_TYPES")]
        public IList<FeatureType> FeatureTypes { get; set; }

        [JsonPropertyName("SUMMARY")]
        public CandidateKeysSummary Summary { get; set; }
    }
}
