// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1
#pragma warning disable CS8601, CS8618

using System.Text.Json;
using System.Text.Json.Serialization;

namespace EntityResolutionSource.Senzing.Models.Typedef
{
    [JsonConverter(typeof(CfgLensrlJsonConverter))]
    public class CfgLensrl
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public IList<Fixme> Value { get; set; }
    }

    public class CfgLensrlJsonConverter : JsonConverter<CfgLensrl>
    {
        public override CfgLensrl Read(
            ref Utf8JsonReader reader,
            Type typeToConvert,
            JsonSerializerOptions options
        )
        {
            return new CfgLensrl
            {
                Value = JsonSerializer.Deserialize<IList<Fixme>>(ref reader, options),
            };
        }

        public override void Write(
            Utf8JsonWriter writer,
            CfgLensrl value,
            JsonSerializerOptions options
        )
        {
            JsonSerializer.Serialize(writer, value.Value, options);
        }
    }
}
