// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1
#pragma warning disable CS8601, CS8618

using System.Text.Json.Serialization;

namespace EntityResolutionSource.Senzing.Models.Typedef
{
    public class DisclosedRelationsForWhyKeyDetails
    {
        [JsonPropertyName("DOMAIN")]
        public string Domain { get; set; }

        [JsonPropertyName("ENTITY_ROLES")]
        public IList<EntityRoles> EntityRoles { get; set; }

        [JsonPropertyName("RELATED_ROLES")]
        public IList<RelatedRoles> RelatedRoles { get; set; }
    }
}
