// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1
#pragma warning disable CS8601, CS8618

using System.Text.Json.Serialization;

namespace EntityResolutionSource.Senzing.Models.Typedef
{
    public class MemberRecord
    {
        /// <summary>
        /// Internal identifier for the record.
        /// </summary>
        [JsonPropertyName("INTERNAL_ID")]
        public int InternalId { get; set; }

        [JsonPropertyName("RECORDS")]
        public IList<Record> Records { get; set; }
    }
}
