// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1
#pragma warning disable CS8601, CS8618

using System.Text.Json.Serialization;

namespace EntityResolutionSource.Senzing.Models.Typedef
{
    public class RecordKeys
    {
        /// <summary>
        /// A list of (data source code, record id) pairs.
        /// </summary>
        [JsonPropertyName("RECORDS")]
        public IList<RecordKey> Records { get; set; }
    }
}
