// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1
#pragma warning disable CS8601, CS8618

using System.Text.Json.Serialization;

namespace EntityResolutionSource.Senzing.Models.Typedef
{
    public class RelatedRoles
    {
        [JsonPropertyName("FEAT_DESC")]
        public string FeatDesc { get; set; }

        [JsonPropertyName("ROLE")]
        public string Role { get; set; }
    }
}
