// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1
#pragma warning disable CS8601, CS8618

using System.Text.Json.Serialization;

namespace EntityResolutionSource.Senzing.Models.Typedef
{
    public class SzDiagnosticGetFeatureResponse
    {
        /// <summary>
        /// Internal use.
        /// </summary>
        [JsonPropertyName("ELEMENTS")]
        public IList<Feature> Elements { get; set; }

        /// <summary>
        /// Internal use.
        /// </summary>
        [JsonPropertyName("FTYPE_CODE")]
        public string FtypeCode { get; set; }

        /// <summary>
        /// Internal use.
        /// </summary>
        [JsonPropertyName("LIB_FEAT_ID")]
        public int LibFeatId { get; set; }
    }
}
