// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1
#pragma warning disable CS8601, CS8618

using System.Text.Json.Serialization;

namespace EntityResolutionSource.Senzing.Models.Typedef
{
    public class SzDiagnosticGetRepositoryInfoResponse
    {
        /// <summary>
        /// A list of database node connection metadata.
        /// </summary>
        [JsonPropertyName("dataStores")]
        public IList<Repository> DataStores { get; set; }
    }
}
