// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1
#pragma warning disable CS8601, CS8618

using System.Text.Json.Serialization;

namespace EntityResolutionSource.Senzing.Models.Typedef
{
    public class SzEngineWhyEntitiesResponse
    {
        [JsonPropertyName("ENTITIES")]
        public IList<Entity> Entities { get; set; }

        [JsonPropertyName("WHY_RESULTS")]
        public IList<WhyResult> WhyResults { get; set; }
    }
}
