// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1
#pragma warning disable CS8601, CS8618

using System.Text.Json.Serialization;

namespace EntityResolutionSource.Senzing.Models.Typedef
{
    public class SzEngineFindPathByEntityIdResponse
    {
        [JsonPropertyName("ENTITIES")]
        public IList<Entity> Entities { get; set; }

        [JsonPropertyName("ENTITY_PATHS")]
        public IList<EntityPath> EntityPaths { get; set; }

        [JsonPropertyName("ENTITY_PATH_LINKS")]
        public IList<EntityPathLink> EntityPathLinks { get; set; }
    }
}
