// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1
#pragma warning disable CS8601, CS8618

using System.Text.Json.Serialization;

namespace EntityResolutionSource.Senzing.Models.Typedef
{
    public class WorkloadRefreshLocks
    {
        [JsonPropertyName("count")]
        public int Count { get; set; }

        [JsonPropertyName("maxMS")]
        public int MaxMs { get; set; }

        [JsonPropertyName("totalMS")]
        public int TotalMs { get; set; }
    }
}
