// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1
#pragma warning disable CS8601, CS8618

using System.Text.Json.Serialization;

namespace EntityResolutionSource.Senzing.Models.Typedef
{
    public class WorkloadProcessingAmbiguous
    {
        [JsonPropertyName("actualTest")]
        public int ActualTest { get; set; }

        [JsonPropertyName("cachedTest")]
        public int CachedTest { get; set; }
    }
}
