// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1
#pragma warning disable CS8601, CS8618

using System.Text.Json.Serialization;

namespace EntityResolutionSource.Senzing.Models.Typedef
{
    public class WorkloadCandidates
    {
        [JsonPropertyName("candidateBuilders")]
        public IDictionary<string, int> CandidateBuilders { get; set; }

        [JsonPropertyName("suppressedCandidateBuilders")]
        public IDictionary<string, int> SuppressedCandidateBuilders { get; set; }
    }
}
