// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1
#pragma warning disable CS8601, CS8618

using System.Text.Json.Serialization;

namespace EntityResolutionSource.Senzing.Models.Typedef
{
    public class WorkloadScoring
    {
        [JsonPropertyName("cacheHit")]
        public IDictionary<string, int> CacheHit { get; set; }

        [JsonPropertyName("cacheMiss")]
        public IDictionary<string, int> CacheMiss { get; set; }

        [JsonPropertyName("scoredPairs")]
        public IDictionary<string, int> ScoredPairs { get; set; }

        [JsonPropertyName("suppressedDisclosedRelationshipDomainCount")]
        public int SuppressedDisclosedRelationshipDomainCount { get; set; }

        [JsonPropertyName("suppressedScoredFeatureType")]
        public Fixme SuppressedScoredFeatureType { get; set; }
    }
}
